# Generated by Django 5.2.17 on 2026-09-18 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolboxEntry',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'use_shared_credential',
                    models.BooleanField(default=False, verbose_name='관리자 공용 키 사용'),
                ),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                (
                    'tool',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entries',
                        to='catalog.tool',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='toolbox',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': '도구함 항목',
                'verbose_name_plural': '도구함 항목',
                'unique_together': {('user', 'tool')},
            },
        ),
        migrations.CreateModel(
            name='ToolSetting',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('key', models.CharField(max_length=60, verbose_name='설정 키')),
                ('ciphertext', models.TextField(verbose_name='암호문')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'entry',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='setting',
                        to='toolbox.toolboxentry',
                    ),
                ),
            ],
            options={
                'verbose_name': '도구 설정',
                'verbose_name_plural': '도구 설정',
            },
        ),
    ]
