# Generated by Django 5.2.17 on 2026-09-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='스코프 이름이자 MCP 도구 이름의 접두',
                        unique=True,
                        verbose_name='식별자',
                    ),
                ),
                ('name', models.CharField(max_length=80, verbose_name='이름')),
                ('description', models.TextField(verbose_name='설명')),
                (
                    'provider',
                    models.CharField(
                        help_text='예: 국가데이터처 KOSIS',
                        max_length=120,
                        verbose_name='데이터 출처',
                    ),
                ),
                (
                    'credential',
                    models.CharField(
                        choices=[
                            ('none', '불요'),
                            ('user', '사용자 키'),
                            ('shared', '사용자 키 또는 관리자 공용 키'),
                        ],
                        default='none',
                        max_length=10,
                        verbose_name='자격증명',
                    ),
                ),
                (
                    'setting_key',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='사용자가 넣는 값의 이름. 예: KOSIS_API_KEY',
                        max_length=60,
                        verbose_name='설정 키',
                    ),
                ),
                ('enabled', models.BooleanField(default=True, verbose_name='공개')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='정렬')),
            ],
            options={
                'verbose_name': '도구',
                'verbose_name_plural': '도구',
                'ordering': ['order', 'slug'],
            },
        ),
    ]
